In [1]:
import numpy as np

In [2]:
arr_contoh = np.arange(12).reshape(3,4)

print(arr_contoh)     #ambil 2 6 10

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print(arr_contoh[:,2].reshape(3,1))

[[ 2]
 [ 6]
 [10]]


In [26]:
test_array = np.arange(12)

print(test_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
print(np.sum(test_array))
print(np.mean(test_array))
print(np.median(test_array))
print(np.max(test_array))
print(np.min(test_array))
print(np.average(test_array))

66
5.5
5.5
11
0
5.5


In [37]:
dadu100 = np.random.random(100)
print(dadu100)
print("")
print(dadu100[10])

[0.06413871 0.18977236 0.15475111 0.52212467 0.31249948 0.45613436
 0.46122367 0.0789155  0.37161922 0.73960391 0.11752526 0.84193248
 0.19676028 0.87062713 0.42893576 0.48530072 0.93534127 0.05859628
 0.19474743 0.0951927  0.52401616 0.83816561 0.05250499 0.6361859
 0.18494958 0.3573783  0.40838767 0.53914683 0.22526162 0.5741604
 0.09660529 0.35308395 0.13820477 0.51672839 0.20752809 0.53097032
 0.17861499 0.20602592 0.96570783 0.13586651 0.70452498 0.81986424
 0.57829848 0.21462316 0.4361458  0.4653729  0.1987218  0.89107586
 0.88462567 0.60209551 0.87515293 0.97544996 0.94653852 0.89811741
 0.06166219 0.31664183 0.77606792 0.75920377 0.71549526 0.31825206
 0.51189307 0.95064189 0.27848233 0.95524109 0.12096196 0.79672552
 0.41782209 0.94745961 0.50161341 0.32943676 0.79528345 0.01622693
 0.84543907 0.81530381 0.03808874 0.14148301 0.37504307 0.54378422
 0.77453979 0.28039423 0.63865693 0.48742463 0.18999774 0.43444727
 0.37166447 0.47338945 0.81788019 0.17163206 0.81019967 0.018903