In [44]:
import numpy as np
import matplotlib as plt
import pandas as pd

In [2]:
arr_contoh = np.arange(12).reshape(3,4)

print(arr_contoh)     #ambil 2 6 10

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [20]:
print(arr_contoh[:,2].reshape(3,1))

[[ 2]
 [ 6]
 [10]]


In [26]:
test_array = np.arange(12)

print(test_array)

[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [31]:
print(np.sum(test_array))
print(np.mean(test_array))
print(np.median(test_array))
print(np.max(test_array))
print(np.min(test_array))
print(np.average(test_array))

66
5.5
5.5
11
0
5.5


In [43]:
dadu100 = np.random.random(100)
print(dadu100)
print("")
print(dadu100[[10,20]])

[0.00185075 0.97262273 0.9644154  0.04532081 0.7093147  0.37941298
 0.5616021  0.41647179 0.66226633 0.87672059 0.70333908 0.97950217
 0.58231018 0.03919793 0.087401   0.20423062 0.13984337 0.04206746
 0.59566231 0.85268286 0.88195535 0.38157797 0.92956866 0.65227688
 0.15191229 0.52589507 0.48277882 0.13939081 0.8638534  0.8385158
 0.01344154 0.16396411 0.11141371 0.55878366 0.20298963 0.57998079
 0.45742973 0.65184184 0.58641318 0.51761109 0.01457092 0.26394247
 0.04173664 0.69667096 0.82147048 0.93398034 0.70797536 0.35302997
 0.06134401 0.64567413 0.02659799 0.75845114 0.96619667 0.90198038
 0.76335002 0.90428358 0.65802841 0.09666638 0.85060974 0.14429972
 0.97458452 0.39614005 0.95139556 0.10657618 0.59381582 0.79645628
 0.34168276 0.87656437 0.6255744  0.48046494 0.69194496 0.76842656
 0.14303129 0.83855642 0.52523557 0.48102903 0.15217899 0.83528698
 0.34116435 0.8585383  0.92597367 0.30844409 0.88984077 0.35715264
 0.47433756 0.28733921 0.7243424  0.83030101 0.54155946 0.47021

In [45]:
a = np.zeros(10)

print(type(a))

<class 'numpy.ndarray'>


In [46]:
b2 = np.zeros((3,4))
print(b2)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [47]:
c = np.ones(8)
c2 = np.random.random((8,3))
c3 = np.empty((2,6))
c4 = np.arange(2,80,2)

print(c)
print(c2)
print(c3)
print(c4)

[1. 1. 1. 1. 1. 1. 1. 1.]
[[0.36330309 0.52947504 0.64088781]
 [0.96058134 0.28070406 0.89425007]
 [0.95220057 0.34423016 0.38815431]
 [0.083391   0.83177148 0.18748385]
 [0.46096732 0.01893831 0.08364995]
 [0.99105365 0.53280687 0.87555191]
 [0.37811046 0.21781809 0.14276152]
 [0.93773205 0.04231983 0.47953752]]
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
[ 2  4  6  8 10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48
 50 52 54 56 58 60 62 64 66 68 70 72 74 76 78]


In [48]:
print (c.shape) #bentuk ada 8 array C
print(c.ndim) #dimensi ada 1 dimensi
print(c.size) #Ukuran ada 8 angka di dalam array C

print(c2.size)
print(c3.shape)
print(c4.ndim)
print(c3.ndim) #2 dimensi

print(c3)
print(c3.shape)
print(c3.ndim)
print(c3.size)

(8,)
1
8
24
(2, 6)
1
2
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]
(2, 6)
2
12


In [49]:
arr_urut = np.array([1,2,3,4,5])

print(arr_urut)

arr_baru = np.append(arr_urut,7)

print(arr_baru)

[1 2 3 4 5]
[1 2 3 4 5 7]


In [50]:
arr_baru2 = np.delete(arr_baru,2)

print(arr_baru2)

arr_acak = ([9,4,1,56,6,2,6,31,12,5,7,3])

arr_urut = np.sort(arr_acak)

print(arr_acak)
print(arr_urut)

[1 2 4 5 7]
[9, 4, 1, 56, 6, 2, 6, 31, 12, 5, 7, 3]
[ 1  2  3  4  5  6  6  7  9 12 31 56]


In [51]:
arr_shape = np.arange(6)

arr_reshaped = arr_shape.reshape((2,3))
arr_reshaped2 = arr_shape.reshape((3,2))

print(arr_shape)
print("")
print(arr_reshaped)
print("")
print(arr_reshaped2)

[0 1 2 3 4 5]

[[0 1 2]
 [3 4 5]]

[[0 1]
 [2 3]
 [4 5]]


In [52]:
# @title
arr_contoh = np.arange(12)

print(arr_contoh)

arr_reshape3 = arr_contoh.reshape(3,4)
print("")
print(arr_reshape3)
print("")
print("Atau dengan cara 1 baris")

arr_contoh2 = np.arange(12).reshape(3,4) #contoh 1 baris code
print("")
print(arr_contoh2)

[ 0  1  2  3  4  5  6  7  8  9 10 11]

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

Atau dengan cara 1 baris

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [53]:
arr_contoh2[2,1] #contoh indexing ( tiap dimensi dimulai dari 0 )

print(arr_contoh2)

arr_contoh2[[0,1]]

arr_contoh2[0:2,1:3] #untuk ambil index 1, 2, 5, 6 (index 0 sampai index 2 dan index 1 sampai index 3)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


array([[1, 2],
       [5, 6]])

In [62]:
matrik_a = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])

matrik_b = np.array([
    [3,2,1],
    [6,5,4],
    [9,8,7]
])

tambah = matrik_a + matrik_b
kurang = matrik_a - matrik_b
kali = matrik_a*matrik_b
bagi = matrik_a/matrik_b
balik = matrik_a.transpose()
balika = matrik_a.T
balikb = matrik_b.transpose()


print(balik)
print("")
print(balika)
print("")
print(tambah)
print("")
print(kurang)
print("")
print(kali)
print("")
print(bagi)
print("")
print(balikb)

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[1 4 7]
 [2 5 8]
 [3 6 9]]

[[ 4  4  4]
 [10 10 10]
 [16 16 16]]

[[-2  0  2]
 [-2  0  2]
 [-2  0  2]]

[[ 3  4  3]
 [24 25 24]
 [63 64 63]]

[[0.33333333 1.         3.        ]
 [0.66666667 1.         1.5       ]
 [0.77777778 1.         1.28571429]]

[[3 6 9]
 [2 5 8]
 [1 4 7]]
